import { Project, Skill, TechStackItem, Experience, Education } from '@/types'

export const skills: Skill[] = [
  {
    name: 'Python',
    src: 'https://cdn.jsdelivr.net/gh/devicons/devicon/icons/python/python-original.svg',
    alt: 'Python',
    external: true,
  },
  {
    name: 'SQL',
    src: 'https://cdn.jsdelivr.net/gh/devicons/devicon/icons/postgresql/postgresql-original.svg',
    alt: 'SQL',
    external: true,
  },
  { name: 'HTML', src: '/images/html.png', alt: 'HTML' },
  { name: 'CSS', src: '/images/css.png', alt: 'CSS' },
  {
    name: 'Tailwind CSS',
    src: 'https://cdn.jsdelivr.net/gh/devicons/devicon/icons/tailwindcss/tailwindcss-original.svg',
    alt: 'Tailwind CSS',
    external: true,
  },
  { name: 'JavaScript', src: '/images/javascript.png', alt: 'JavaScript' },
  { name: 'React', src: '/images/react.png', alt: 'React' },
  {
    name: 'Next.js',
    src: 'https://cdn.jsdelivr.net/gh/devicons/devicon/icons/nextjs/nextjs-original.svg',
    alt: 'Next.js',
    external: true,
  },
  {
    name: 'Node.js',
    src: 'https://cdn.jsdelivr.net/gh/devicons/devicon/icons/nodejs/nodejs-original.svg',
    alt: 'Node.js',
    external: true,
  },
  {
    name: 'Express',
    src: 'https://cdn.jsdelivr.net/gh/devicons/devicon/icons/express/express-original.svg',
    alt: 'Express.js',
    external: true,
  },
  {
    name: 'MongoDB',
    src: 'https://cdn.jsdelivr.net/gh/devicons/devicon/icons/mongodb/mongodb-original.svg',
    alt: 'MongoDB',
    external: true,
  },
  {
    name: 'Prisma',
    src: 'https://cdn.jsdelivr.net/gh/devicons/devicon/icons/prisma/prisma-original.svg',
    alt: 'Prisma',
    external: true,
  },
  {
    name: 'Firebase',
    src: 'https://cdn.jsdelivr.net/gh/devicons/devicon/icons/firebase/firebase-plain.svg',
    alt: 'Firebase',
    external: true,
  },
  { name: 'Framer Motion', src: '/images/framer-motion.svg', alt: 'Framer Motion' },
  {
    name: 'TypeScript',
    src: 'https://cdn.jsdelivr.net/gh/devicons/devicon/icons/typescript/typescript-original.svg',
    alt: 'TypeScript',
    external: true,
  },
  {
    name: 'PostgreSQL',
    src: 'https://cdn.jsdelivr.net/gh/devicons/devicon/icons/postgresql/postgresql-original.svg',
    alt: 'PostgreSQL',
    external: true,
  },
  {
    name: 'Docker',
    src: 'https://cdn.jsdelivr.net/gh/devicons/devicon/icons/docker/docker-original.svg',
    alt: 'Docker',
    external: true,
  },
  {
    name: 'Google Cloud',
    src: 'https://cdn.jsdelivr.net/gh/devicons/devicon/icons/googlecloud/googlecloud-original.svg',
    alt: 'Google Cloud',
    external: true,
  },
  {
    name: 'Redis',
    src: 'https://cdn.jsdelivr.net/gh/devicons/devicon/icons/redis/redis-original.svg',
    alt: 'Redis',
    external: true,
  },
  {
    name: 'Three.js',
    src: 'https://threejs.org/files/logo.png',
    alt: 'Three.js',
    external: true,
  },
  {
    name: 'LangChain',
    src: 'https://avatars.githubusercontent.com/u/126733545?s=200&v=4',
    alt: 'LangChain',
    external: true,
  },
  {
    name: 'LangGraph',
    src: 'https://langchain-ai.github.io/langgraph/img/favicon.ico',
    alt: 'LangGraph',
    external: true,
  },
  {
    name: 'React Query',
    src: 'https://cdn.jsdelivr.net/gh/devicons/devicon/icons/react/react-original.svg',
    alt: 'React Query',
    external: true,
  },
  {
    name: 'Zustand',
    src: 'https://avatars.githubusercontent.com/u/44566809?s=200&v=4',
    alt: 'Zustand',
    external: true,
  },
  {
    name: 'shadcn/ui',
    src: 'https://ui.shadcn.com/favicon.ico',
    alt: 'shadcn/ui',
    external: true,
  },
]

export const fullstackProjects: Project[] = [
  {
    title: 'Recipia - AI-Powered Recipe App',
    image: '/images/recipia.png',
    alt: 'Recipia - AI-powered recipe app',
    liveUrl: 'https://recipe-app-kappa-cyan.vercel.app/',
    category: 'Fullstack',
    tags: ['Fullstack', 'AI Recipe Discovery'],
    description: 'Built an AI-powered chatbot with multimodal input (voice/image) for interactive recipe discovery and verified cooking reviews. Integrated Google Calendar API for real-time meal planning and scheduling. Developed a full-stack AI recipe platform with RBAC, personalized dashboards, and collaborative features.',
    techStack: [
      { name: 'Next.js', src: 'https://cdn.jsdelivr.net/gh/devicons/devicon/icons/nextjs/nextjs-original.svg', external: true },
      { name: 'MongoDB', src: 'https://cdn.jsdelivr.net/gh/devicons/devicon/icons/mongodb/mongodb-original.svg', external: true },
      { name: 'TypeScript', src: 'https://cdn.jsdelivr.net/gh/devicons/devicon/icons/typescript/typescript-original.svg', external: true },
      { name: 'LangChain', src: 'https://avatars.githubusercontent.com/u/126733545?s=200&v=4', external: true },
    ],
  },
  {
    title: 'OMO AI - Marketing Intelligence',
    image: '/images/omo-ai.png',
    alt: 'OMO AI - Marketing AI',
    liveUrl: 'https://omo-ai-web-xi.vercel.app/',
    category: 'Fullstack',
    tags: ['Fullstack', 'AI Marketing Platform'],
    description: 'Co-developed an intensive AI-powered chatbot platform for businesses to track and manage ad performance and engagement in real time. Built a comprehensive authentication and onboarding system with secure sessions, OAuth via Google Cloud, and role-based access control. Implemented a dynamic settings module and an admin dashboard for robust user and data management.',
    techStack: [
      { name: 'Next.js', src: 'https://cdn.jsdelivr.net/gh/devicons/devicon/icons/nextjs/nextjs-original.svg', external: true },
      { name: 'TypeScript', src: 'https://cdn.jsdelivr.net/gh/devicons/devicon/icons/typescript/typescript-original.svg', external: true },
      { name: 'Prisma', src: 'https://cdn.jsdelivr.net/gh/devicons/devicon/icons/prisma/prisma-original.svg', external: true },
      { name: 'PostgreSQL', src: 'https://cdn.jsdelivr.net/gh/devicons/devicon/icons/postgresql/postgresql-original.svg', external: true },
      { name: 'Docker', src: 'https://cdn.jsdelivr.net/gh/devicons/devicon/icons/docker/docker-original.svg', external: true },
      { name: 'Google Cloud', src: 'https://cdn.jsdelivr.net/gh/devicons/devicon/icons/googlecloud/googlecloud-original.svg', external: true },
    ],
  },
  {
    title: 'NSIA Insurance Customer Portal',
    image: '/images/nsia-customer-portal.png',
    alt: 'NSIA Insurance Customer Portal',
    liveUrl: 'https://dev.nsiainsurance.com.ng/',
    category: 'Fullstack',
    tags: ['Fullstack', 'Insurance Portal'],
    description: 'Architected and building a customer portal for seamless purchase and management of insurance policies, leveraging Node.js, Express.js, PostgreSQL, Redis, BullMQ for background policy document processing and scalability. Automated internal GIT portal processes with bulk-upload tools, reducing manual entry time by 75%.',
    techStack: [
      { name: 'Next.js', src: 'https://cdn.jsdelivr.net/gh/devicons/devicon/icons/nextjs/nextjs-original.svg', external: true },
      { name : 'TypeScript', src: 'https://cdn.jsdelivr.net/gh/devicons/devicon/icons/typescript/typescript-original.svg', external: true },
      { name: 'Node.js', src: 'https://cdn.jsdelivr.net/gh/devicons/devicon/icons/nodejs/nodejs-original.svg', external: true },
      { name: 'PostgreSQL', src: 'https://cdn.jsdelivr.net/gh/devicons/devicon/icons/postgresql/postgresql-original.svg', external: true },
      { name: 'Redis', src: 'https://cdn.jsdelivr.net/gh/devicons/devicon/icons/redis/redis-original.svg', external: true },
    ],
  },
  {
    title: 'Dev Link - Link Sharing App',
    image: '/images/devlink.png',
    alt: 'Dev Link - Link sharing app',
    liveUrl: '#',
    category: 'Fullstack',
    tags: ['Fullstack', 'Link Management'],
    description: 'Built public profiles with verified links, authentication, and shareable URLs to boost user visibility. Designed a link management system enabling users to verify and publicly share key resources with drag-and-drop functionality and real-time previews.',
    techStack: [
      { name: 'Next.js', src: 'https://cdn.jsdelivr.net/gh/devicons/devicon/icons/nextjs/nextjs-original.svg', external: true },
      { name: 'TypeScript', src: 'https://cdn.jsdelivr.net/gh/devicons/devicon/icons/typescript/typescript-original.svg', external: true },
      { name: 'Firebase', src: 'https://cdn.jsdelivr.net/gh/devicons/devicon/icons/firebase/firebase-plain.svg', external: true },
    ],
  },
  {
    title: 'Ace Stores (Ecommerce web app)',
    image: '/images/ace-stores.png',
    alt: 'Ace stores',
    liveUrl: 'https://ace-stores.vercel.app/',
    category: 'Fullstack',
    tags: ['Fullstack', 'Ecommerce Web App'],
    description: 'Implemented secure user authentication, cart/order management, and Paystack checkout, supporting real transactions. Converted Figma wireframes into a responsive, pixel-perfect user interface.',
    techStack: [
      { name: 'React', src: 'https://cdn.jsdelivr.net/gh/devicons/devicon/icons/react/react-original.svg', external: true },
      { name: 'TypeScript', src: 'https://cdn.jsdelivr.net/gh/devicons/devicon/icons/typescript/typescript-original.svg', external: true },
      { name: 'Firebase', src: 'https://cdn.jsdelivr.net/gh/devicons/devicon/icons/firebase/firebase-plain.svg', external: true },
    ],
    sourceCode: 'https://github.com/owoadehabeeb04/ace-store',
  },

]

export const frontendProjects: Project[] = [
  {
    title: 'Solar Survey AI',
    image: '/images/solarsurvey.png',
    alt: 'Solar Survey AI',
    liveUrl: 'https://www.solarsurvey.ai/',
    category: 'Frontend',
    tags: ['Frontend', 'AI-Driven Drone Surveys'],
    description: 'Engineered an interactive 3D globe explorer using React, Three.js, TypeScript, enabling real-time visualization of solar projects across geographies. Launched a scalable PWA supporting offline mode for technicians, improving field usability by 40%. Integrated Google Maps API and WebSockets to deliver precise mapping and real-time upload feedback.',
    techStack: [
      { name: 'React', src: 'https://cdn.jsdelivr.net/gh/devicons/devicon/icons/react/react-original.svg', external: true },
      { name: 'TypeScript', src: 'https://cdn.jsdelivr.net/gh/devicons/devicon/icons/typescript/typescript-original.svg', external: true },
{name: 'Tailwind CSS', src: 'https://cdn.jsdelivr.net/gh/devicons/devicon/icons/tailwindcss/tailwindcss-original.svg', external: true },
    ],
  },
  {
    title: 'CrewLink - Field Team Management',
    image: '/images/crewlink.png',
    alt: 'CrewLink',
    liveUrl: 'https://www.crewlink.ai/',
    category: 'Frontend',
    tags: ['Frontend', 'Team Management Platform'],
    description: 'Developed a comprehensive field team management platform with real-time tracking, task assignment, and communication features. Built responsive interfaces for mobile and desktop to streamline field operations and improve team coordination.',
    techStack: [
      { name: 'React', src: 'https://cdn.jsdelivr.net/gh/devicons/devicon/icons/react/react-original.svg', external: true },
      { name: 'TypeScript', src: 'https://cdn.jsdelivr.net/gh/devicons/devicon/icons/typescript/typescript-original.svg', external: true },
{name: 'Tailwind CSS', src: 'https://cdn.jsdelivr.net/gh/devicons/devicon/icons/tailwindcss/tailwindcss-original.svg', external: true },
    ],
  },
  {
    title: 'Tobi Owoade Portfolio',
    image: '/images/tobiowoade.png',
    alt: 'Tobi Owoade Portfolio',
    liveUrl: 'https://www.tobiowoade.com/',
    category: 'Frontend',
    tags: ['Frontend', 'Portfolio Website'],
    description: 'Designed and developed a modern, responsive portfolio website showcasing creative work and professional experience. Implemented smooth animations, interactive elements, and a clean, editorial design aesthetic.',
  },
]

export const experiences: Experience[] = [
  {
    title: 'Software Engineer',
    company: 'Solar Survey AI',
    location: 'Illinois, USA',
    type: 'Remote',
    startDate: 'Sept 2024',
    endDate: 'Dec 2025',
    achievements: [
      'Engineered an interactive 3D globe explorer using React, Three.js, TypeScript, enabling real-time visualization of solar projects across geographies',
      'Launched a scalable PWA supporting offline mode for technicians, improving field usability by 40%',
      'Developed an admin dashboard with bulk uploads, automated image exports (400+ images), and granular user controls, streamlining content management',
      'Integrated Google Maps API and WebSockets to deliver precise mapping and real-time upload feedback',
    ],
  },
  {
    title: 'Software Engineer',
    company: 'Omo AI',
    location: 'Remote',
    type: 'Contract',
    startDate: 'July 2025',
    endDate: 'Oct 2025',
    achievements: [
      'Co-developed an intensive AI-powered chatbot platform for businesses to track and manage ad performance and engagement in real time',
      'Built a comprehensive authentication and onboarding system with secure sessions, OAuth via Google Cloud, and role-based access control',
      'Implemented a dynamic settings module and an admin dashboard for robust user and data management',
      'Leveraged Prisma ORM, PostgreSQL, Docker, Next.js, LangChain, and Google Cloud Platform for scalable backend and AI integration',
      'Collaborating with a small engineering team to refine chatbot workflows, automate feedback loops, and enhance analytics accuracy',
    ],
  },
  {
    title: 'Enterprise Software Engineer Intern',
    company: 'NSIA Insurance',
    location: 'Lagos, Nigeria',
    type: 'Intern',
    startDate: 'Mar 2025',
    endDate: 'Aug 2025',
    achievements: [
      'Architected and building a customer portal for seamless purchase and management of insurance policies, leveraging Node.js, Express.js, PostgreSQL, Redis, BullMQ for background policy document processing and scalability',
      'Automated internal GIT portal processes with bulk-upload tools, reducing manual entry time by 75%',
      'Designed and deployed a corporate blog platform using React.js, Tailwind CSS, enhancing brand visibility and engagement',
      'Partnered with IT and design teams to roll out a standardized email signature system for 300+ employees, ensuring consistent branding',
    ],
  },
  {
    title: 'Frontend Engineer',
    company: 'Chef4Me',
    location: 'Lagos, Nigeria',
    type: 'Remote',
    startDate: 'Sept 2023',
    endDate: 'Oct 2024',
    achievements: [
      'Built a scalable LMS platform for 1,000+ users, supporting real-time notifications, course creation, and progress tracking',
      'Boosted system responsiveness by 70% through optimized REST API integrations and frontend query improvements',
      'Increased website performance and user experience by 80% via frontend optimization and lazy loading techniques',
      'Developed a full admin dashboard for user, cart, and order management, improving internal operations',
    ],
  },
  {
    title: 'Frontend Engineer Intern (Finalist)',
    company: 'HNG Technologies',
    location: 'Lagos, Nigeria',
    type: 'Remote',
    startDate: 'June 2024',
    endDate: 'Aug 2024',
    achievements: [
      'Ranked in the Top 500 out of 30,000+ participants during competitive internship program',
      'Built an e-commerce application integrating Timbu API with React (Vite), TypeScript, Tailwind CSS, supporting real-time inventory and checkout flows',
      'Developed DelveFun, a full-stack language learning platform with authentication, progress tracking, and an admin dashboard for course management',
    ],
  },
]

export const education: Education = {
  institution: 'Bowen University',
  degree: 'B.Sc. Software Engineering',
  location: 'Nigeria',
  startDate: 'Oct 2022',
  endDate: 'Present',
  cgpa: '4.65 / 5.00 (Top 1%)',
  highlights: [
    'First runner-up in TechHub Frontend Hackathon (20+ students)',
    'Courses: Data Structures, Web Technologies, Algorithms, Computer Architecture',
  ],
}

